// Code generated by moq; DO NOT EDIT.
// gitlab.diskarte.net/engineering/moqc fork from github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/donmikel/wow/applications/server"
)

var _ server.Service = &Service{}

// Service is a mock implementation of server.Service.
type Service struct {
	// GetQuoteFn mocks the GetQuote method.
	GetQuoteFn func() string

	// calls tracks calls to the methods.
	calls struct {
		// GetQuote holds details about calls to the GetQuote method.
		GetQuote []struct {
		}
	}
	lockGetQuote sync.RWMutex
}

// GetQuote calls GetQuoteFn.
func (mock *Service) GetQuote() string {
	callInfo := struct {
	}{}
	mock.lockGetQuote.Lock()
	mock.calls.GetQuote = append(mock.calls.GetQuote, callInfo)
	mock.lockGetQuote.Unlock()
	if mock.GetQuoteFn == nil {
		var (
			out1 string
		)
		return out1
	}
	return mock.GetQuoteFn()
}

// GetQuoteCalls gets all the calls that were made to GetQuote.
// Check the length with:
//
//	len(mockedService.GetQuoteCalls())
func (mock *Service) GetQuoteCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetQuote.RLock()
	calls = mock.calls.GetQuote
	mock.lockGetQuote.RUnlock()
	return calls
}
